### ISSUE TITLE
Do not work with touch-screen in IE11 or Edge

### ISSUE THREAD

**Issue by icozarir** [bencentra/jq-signature#6]
Hello.

Thanks for a very good signature tool!

We found out that it doesn't work in IE11 or Edge on a touch-screen (Windows 10). Works fine in Chrome.

Do you have any suggestions?

Best regards Anders

**Comment by icozarir** [comment]
#7

**Comment by bencentra** [comment]
Thanks again for the PR! I still had issues with a Windows Phone (8.1) in an emulator - it would draw the signature, but kinda drag the screen around a bit.

**Comment by icozarir** [comment]
Yes we had the same issue but found out that we were missing:
 style="-ms-touch-action: none". I wasn't sure how to add it to the .js code so we added it on the containing DIV. Hope that helps.

**Comment by bencentra** [comment]
Fixed in https://github.com/bencentra/jq-signature/commit/65252b5a49b0771014773a60acb6979f542534a0
